language: go

go:
  - 1.7
  - 1.8
  - tip

install:
  - export PATH=$GOPATH/bin:$PATH
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get github.com/gin-gonic/gin

script: cd demo && make assets && cd - &&  ginkgo -r --randomizeSuites --race --trace
